### ISSUE TITLE
Class-based Components

### ISSUE THREAD

**Issue by loreanvictor** [loreanvictor/callbag-jsx#11]
> Are there any plans to support classes as components when rendering the JSX? All examples seem to use a function that gets the props and renderer and returns what should be rendered. Have you considered supporting classes as well? For example, if the class has a method "render" it could be called with the props and renderer arguments, maybe. Some people might prefer classes over function for organizing their sources...
>
> This is not a big deal, since it should be easy to create a wrapper for such classes (so that we could do something like this after defining the class `const ComponentRenderer = wrapper(ComponentClass);`, but it might be interesting to support it out of the box...

_Originally posted by @rosenfeld in https://github.com/loreanvictor/callbag-jsx/issues/9#issuecomment-812222252_

**Comment by rosenfeld** [comment]
I just found this: https://loreanvictor.github.io/callbag-jsx/in-depth/renderer

There's a section about a plugin to allow for a component-based approach.

**Comment by loreanvictor** [comment]
> I just found this: https://loreanvictor.github.io/callbag-jsx/in-depth/renderer
> 
> There's a section about a plugin to allow for a component-based approach.

I was writing about the same thing :)) Yes, you can extend behavior of `renderer`s via plugins, for [example](https://loreanvictor.github.io/callbag-jsx/in-depth/renderer#example-class-based-components) a plugin can provide support for class based components.

I think it would also be a good idea to publish a package for such a plugin, but for now I don't see any benefits in providing the feature out of the box. I generally believe a bunch of integrating but independently maintained libraries will remain more agile and will be managed more efficiently (for example its easier to make changes to small libraries, its easier for new contributors to start contributing if the library is small, etc).

**Comment by rosenfeld** [comment]
Yes, but for tutorials/documentation purposes, I don't see component authors showing examples with class-based components unless they are supported out-of-the-box, for example...

**Comment by loreanvictor** [comment]
I think component authors would need to specifically provide each type of component, so I suspect IF a component author also provides a class-based version of a component, they would document it as well. It is notable that this would of course require a _standard_ class-based plugin that any component author could rely on.

**Comment by loreanvictor** [comment]
Ok I'll move this to discussions for now.
